safer use of api library + fixed panic
Rhymen/go-whatsapp pull request #512
Opened 2021-01-24 03:55 UTC by artem-webdev

# what do you think, maybe you shouldn't return nil, but rather close the channel?

#### Here is my suggestion. Api will be safer, especially for novice programmers
#### in this case it will not be necessary to return the function before reading from the channel
```
go function(){

       chanRead, err := wac.Read(message.Info.RemoteJid, message.Info.Id)
        if err != nil {
            log.Println(err)   
       }

        // there will be no blocking even with this error ! 
        <-chanRead

}()

```

### in the current implementation with explicit nil
``` 
go function(){

       chanRead, err := wac.Read(message.Info.RemoteJid, message.Info.Id)
        if err != nil {
            log.Println(err)   
       }

        // nil channel leading to eternal blocking in case of programmer error ! 
        <-chanRead

}()

```

2021-01-24 03:56 UTC, artem-webdev commented
I apologize for the many titles, I just didn't get enough sleep here is the latest version

2021-01-24 03:59 UTC, beshoo commented
Again, how l see the panic on the current lib.
You are talking about "security" what is the security leak?

I can not see how can l approve this pl

2021-01-24 04:04 UTC, artem-webdev commented
не закрывайте pl так быстро, вы можете увидеть изменения здесь https://github.com/Rhymen/go-whatsapp/pull/512/files , если вы не видите исправленных ошибок в коде, я могу !

2021-01-24 04:08 UTC, artem-webdev commented
what exactly is not clear to you from the first comment with code examples?

2021-01-24 04:11 UTC, beshoo commented
I closed the pl when it is NOT organized, l have no problem with the pl it self.
Thank you, but anyway, l stll can not see the ""security"" problem which you are referring to. Nor how panic may happens. Show us a panic report whuch you addressed with this PL.

Thanks

2021-01-24 04:18 UTC, beshoo commented
My question is straightforward.
Where is the security lake? 
Whats is the panic you are addressing? 
What is the panic report? 

That is the title of the PL, if you are fine tuning the api then please tell the expected result. 

Regard

2021-01-24 04:22 UTC, artem-webdev commented
if you are not good at code, then let others see it, it's still an open source project!

2021-01-24 04:30 UTC, beshoo commented
I do appreciate your Pl, an i am good in golang, but that's is not the problem,
Your modification is appreciated. 
Any way l will let the community to decide. 
I can not approve this PL since it lake of details.

2021-01-26 10:34 UTC, SchulteMK requested changes
I agree that returning a closed channel is better than a nil channel.

Backround:
- Reading from a channel that is `nil ` (or not initialized) is not possible
  - if you try, you will wait forever
  - if you use select, that branch never gets selected 
- Reading from a closed channel will return instantly with the null-value of the channel type
  - it would never block

[Source](https://nanxiao.gitbooks.io/golang-101-hacks/content/posts/nil-channel-vs-closed-channel.html)

2021-01-26 17:33 UTC, artem-webdev commented on read.go
>  		wac.listener.Unlock()
thanks for your understanding, added your recommendation !

2021-01-26 17:44 UTC, SchulteMK approved these changes

2021-01-26 17:44 UTC, merged